Models/Transaccion.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuesto.Models
{
    public class Transaccion
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        [Range(1, maximum: int.MaxValue, ErrorMessage = "Debe seleccionar una cuenta")]
        [Display(Name = "Cuentas")]
        public int IdCuenta { get; set; }
        [Range(1, maximum: int.MaxValue, ErrorMessage ="Debe seleccionar una categoria")]
        [Display(Name = "Categorias")]
        public int IdCategoria { get; set; }
        [StringLength(maximumLength:1000, ErrorMessage ="La nota no puede pasar de {1} caracteres")]
        public string Nota { get; set; }
        public decimal Monto { get; set; }
        [Display(Name ="Fecha Transaccion")]
        [DataType(DataType.Date)]
        public DateTime FechaTransaccion { get; set; } = DateTime.Today;
        public DateTime Create_at { get; set; }
        [Display(Name = "Tipo Operacion")]
        public TipoOperacion IdTipoOperacion { get; set; } = TipoOperacion.Ingreso;
        public string Cuenta { get; set; }
        public string Categoria { get; set; }
    }
}

Controllers/TransaccionController.cs
using AutoMapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection;
using System.Transactions;

namespace ManejoPresupuesto.Controllers
{
    public class TransaccionController : Controller
    {
        private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioUsuarios servicioUsuarios;
        private readonly IRepositorioCuentas repositorioCuentas;
        private readonly IRepositorioCategorias repositorioCategorias;
        private readonly IMapper mapper;

        public TransaccionController(IRepositorioTransacciones repositorioTransacciones, IServicioUsuarios servicioUsuarios, IRepositorioCuentas repositorioCuentas, IRepositorioCategorias repositorioCategorias, IMapper mapper)
        {
            this.repositorioTransacciones = repositorioTransacciones;
            this.servicioUsuarios = servicioUsuarios;
            this.repositorioCuentas = repositorioCuentas;
            this.repositorioCategorias = repositorioCategorias;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(int mes, int year)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            DateTime fechaInicio;
            DateTime fechaFin;
            if (mes <= 0 || mes > 12 || year <= 1900)
            {
                var hoy = DateTime.Today;
                fechaInicio = new DateTime(hoy.Year, hoy.Month, 1);
            }
            else
            {
                fechaInicio = new DateTime(year, mes, 1);
            }
            fechaFin = fechaInicio.AddMonths(1).AddDays(-1);
            var parametro = new ParametroObtenerTransaccionesPorUsuario()
            {
                IdUsuario = idUsuario,
                FechaInicio = fechaInicio,
                FechaFin = fechaFin,
            };
            var transacciones = await repositorioTransacciones.ObtenerPorIdUsuario(parametro);
            var modelo = new ReporteTransaccionesDetalladas();
            var transaccionesPorFecha = transacciones.OrderByDescending(x => x.FechaTransaccion).GroupBy(x => x.FechaTransaccion).Select(grupo => new ReporteTransaccionesDetalladas.TransaccionesPorFecha() { FechaTransaccion = grupo.Key, Transacciones = grupo.AsEnumerable() });
            modelo.TransaccionesAgrupadas = transaccionesPorFecha;
            modelo.FechaInicio = fechaInicio;
            modelo.FechaFin = fechaFin;

            ViewBag.mesAnterior = fechaInicio.AddMonths(-1).Month;
            ViewBag.yearAnterior = fechaInicio.AddMonths(-1).Year;
            ViewBag.mesPosterior = fechaInicio.AddMonths(1).Month;
            ViewBag.yearPosterior = fechaInicio.AddMonths(1).Year;
            ViewBag.urlRetorno = HttpContext.Request.Path + HttpContext.Request.QueryString;
            return View(modelo);
        }
        public async Task<IActionResult> Crear()
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            var modelo = new TransaccionCreacionViewModel();
            modelo.Cuenta = await ObtenerCuentas(idUsuario);
            modelo.Categorias = await ObtenerCategorias(idUsuario, modelo.IdTipoOperacion);
            return View(modelo);
        }
        [HttpPost]
        public async Task<IActionResult> Crear(TransaccionCreacionViewModel modelo)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            if (!ModelState.IsValid)
            {
                modelo.Cuenta = await ObtenerCuentas(idUsuario);
                modelo.Categorias = await ObtenerCategorias(idUsuario, modelo.IdTipoOperacion);
                return View(modelo);
            }
            var cuenta = await repositorioCuentas.ObtenerPorId(modelo.IdCuenta, idUsuario);
            if( cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var categoria = await repositorioCategorias.Buscar(modelo.IdCategoria, idUsuario);
            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            modelo.IdUsuario = idUsuario;
            if(modelo.IdTipoOperacion == TipoOperacion.Gasto)
            {
                modelo.Monto *= -1;
            }
            await repositorioTransacciones.Crear(modelo);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Editar(int id, string urlRetorno = null)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            var transaccion = await repositorioTransacciones.ObtenerPorId(id, idUsuario);
            if (transaccion is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var modelo = mapper.Map<TransaccionesActualizacionViewModel>(transaccion);
            modelo.MontoAnterior = modelo.Monto;
            if (modelo.IdTipoOperacion == TipoOperacion.Gasto)
            {
                modelo.MontoAnterior = modelo.Monto * -1;
            }
            modelo.IdCuentaAnterior = transaccion.IdCuenta;
            modelo.Categorias = await ObtenerCategorias(idUsuario,transaccion.IdTipoOperacion);
            modelo.Cuenta = await ObtenerCuentas(idUsuario);
            modelo.UrlRetorno = urlRetorno;
            return View(modelo);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(TransaccionesActualizacionViewModel modelo)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            if (!ModelState.IsValid)
            {
                modelo.Cuenta = await ObtenerCuentas(idUsuario);
                modelo.Categorias = await ObtenerCategorias(idUsuario, modelo.IdTipoOperacion);
                return View(modelo);
            }
            var cuenta = await repositorioCuentas.ObtenerPorId(modelo.IdCuenta, idUsuario);
            if(cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var categoria = await repositorioCategorias.Buscar(modelo.IdCategoria, idUsuario);
            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var transaccion = mapper.Map<Transaccion>(modelo);
            if (modelo.IdTipoOperacion == TipoOperacion.Gasto)
            {
                transaccion.Monto *= -1;
            }
            await repositorioTransacciones.Actualizar(transaccion, modelo.MontoAnterior, modelo.IdCuentaAnterior);
            if (string.IsNullOrEmpty(modelo.UrlRetorno))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return LocalRedirect(modelo.UrlRetorno);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Borrar(int id, string urlRetorno = null)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            var transaccion = await repositorioTransacciones.ObtenerPorId(id, idUsuario);
            if (transaccion is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioTransacciones.Borrar(id);

            if (string.IsNullOrEmpty(urlRetorno))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return LocalRedirect(urlRetorno);
            }
            return RedirectToAction("Index");
        }
        private async Task<IEnumerable<SelectListItem>> ObtenerCuentas(int idUsuario)
        {
            var cuentas = await repositorioCuentas.Buscar(idUsuario);
            return cuentas.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }
        private async Task<IEnumerable<SelectListItem>> ObtenerCategorias(int idUsuario, TipoOperacion tipoOperacion)
        {
            var categorias = await repositorioCategorias.Obtener(idUsuario, tipoOperacion);
            return categorias.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }

        [HttpPost]
        public async Task<IActionResult> ObtenerCategorias([FromBody] TipoOperacion tipoOperacion)
        {
            var idUsuario = servicioUsuarios.ObtenerIdUsuario();
            var categorias = await ObtenerCategorias(idUsuario, tipoOperacion);
            return Ok(categorias);
        }
    }
}

Views/Transaccion/Crear.cshtml
@model TransaccionCreacionViewModel
@{
    ViewData["TiTle"] = "Crear Transaccion";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 mt-5">
            <div class="card shadow-lg border-0">
                <div class="card-header text-center"><h2>Crear Cuenta</h2></div>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <p class="card-text">
                        <form asp-controller="Transaccion" asp-action="Crear" method="post">
                            <div class="row">
                                <div class="col-6">
                                    <div class="mb-3">
                                        <label asp-for="FechaTransaccion" class="form-label"></label>
                                        <input asp-for="FechaTransaccion" class="form-control" />
                                        <span asp-validation-for="FechaTransaccion" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="IdCuenta" class="form-label"></label>
                                        <select asp-for="IdCuenta" asp-items="Model.Cuentas" class="form-select"></select>
                                        <span asp-validation-for="IdCuenta" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="IdTipoOperacion" class="form-label"></label>
                                        <select asp-for="IdTipoOperacion" asp-items="Html.GetEnumSelectList<TipoOperacion>()" class="form-select"></select>
                                        <span asp-validation-for="IdCuenta" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="mb-3">
                                        <label asp-for="Cuentas" class="form-label"></label>
                                        <select asp-for="Cuentas" class="form-select"></select>
                                        <span asp-validation-for="Cuentas" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="Monto" class="form-label"></label>
                                        <input asp-for="Monto" class="form-control" />
                                        <span asp-validation-for="Monto" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="Nota" class="form-label"></label>
                                        <textarea asp-for="Nota" class="form-control" style="height: 100px"></textarea>
                                        <span asp-validation-for="Nota" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Transaccion/Editar.cshtml
@model TransaccionesActualizacionViewModel
@{
    ViewData["TiTle"] = "Editar Transaccion";
    var linkCancelar = Model.UrlRetorno ?? Url.Action("Index");
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 mt-5">
            <div class="card shadow-lg border-0">
                <div class="card-header text-center"><h2>Editar Transaccion</h2></div>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <p class="card-text">
                        <form asp-action="Editar" method="post">
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="MontoAnterior" />
                            <input type="hidden" asp-for="IdCuentaAnterior" />
                            <input type="hidden" asp-for="UrlRetorno" />
                            <div class="row">
                                <div class="col-6">
                                    <div class="mb-3">
                                        <label asp-for="FechaTransaccion" class="form-label"></label>
                                        <input asp-for="FechaTransaccion" class="form-control" />
                                        <span asp-validation-for="FechaTransaccion" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="IdCuenta" class="form-label"></label>
                                        <select asp-for="IdCuenta" asp-items="Model.Cuenta" class="form-select"></select>
                                        <span asp-validation-for="IdCuenta" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="IdTipoOperacion" class="form-label"></label>
                                        <select asp-for="IdTipoOperacion" id="IdTipoOperacion" asp-items="Html.GetEnumSelectList<TipoOperacion>()" class="form-select"></select>
                                        <span asp-validation-for="IdCuenta" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="mb-3">
                                        <label asp-for="IdCategoria" class="form-label"></label>
                                        <select class="form-select" asp-for="IdCategoria"></select>
                                        <span asp-validation-for="IdCategoria" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="Monto" class="form-label"></label>
                                        <input asp-for="Monto" class="form-control" />
                                        <span asp-validation-for="Monto" class="text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label asp-for="Nota" class="form-label"></label>
                                        <textarea asp-for="Nota" class="form-control" style="height: 100px"></textarea>
                                        <span asp-validation-for="Nota" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <div class="row justify-content-between">
                                        <div class="col-6">
                                            <div class="row">
                                                <div class="col-6">
                                                    <a href="@linkCancelar" class="btn btn-outline-secondary form-control">Cancelar</a>
                                                </div>
                                                <div class="col-6">
                                                        <button class="btn btn-outline-danger form-control" asp-action="Borrar">Borrar</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <button class="btn btn-outline-success form-control">Actualizar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/FormularioTransacciones.js" asp-append-version="true"></script>
    <script>
        const urlObtenerCategorias = '@Url.Action("ObtenerCategorias")';
        $(function(){
            inicializarFormilarioTransacciones(urlObtenerCategorias)
        });
    </script>
}

Views/Transaccion/Index.cshtml
@model ReporteTransaccionesDetalladas
@{
    ViewData["Title"] = "Reporte Diario";
}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 class="fw-bold">Indice de Transacciones</h1>
        </div>
        <div class="col-12 mt-3">
            <a asp-action="crear" class="btn btn-outline-secondary btn-lg form-control"><i class="bi bi-plus-circle-fill"></i> Crear Transaccion</a>
        </div>
    </div>
</div>
<partial name="_ReporteTransaccionesDetalladas" model="Model" />